### ISSUE TITLE
Alamofire beta 

### ISSUE THREAD

**Issue by francodriansetti** [inplayer-org/inplayer-ios-sdk#37]
Hi, 

I'm getting an issue when I try to import the inlayer sdk

This is how my pod file look like: 
![Screenshot 2019-11-04 at 12 14 51](https://user-images.githubusercontent.com/7194678/68117088-b564b300-fefc-11e9-810b-8758446e72ef.png)

And this is the error I'm getting when I run `pod install`

![Screenshot 2019-11-04 at 12 15 39](https://user-images.githubusercontent.com/7194678/68117141-d3321800-fefc-11e9-8b59-622ed51752f5.png)

Is possible to have a SDK version that is using latest stable Alamofire version: 5.0.0-rc.3? 

Thank you 
Franco

**Comment by odimitrov** [comment]
Hello @francodriansetti, we have taken care of it. You can try the latest 1.5.0 version already pushed to Cocoapods.
